services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    # Network mode host allows access to other services on the host easily
    # and simplifies the pipe setup
    network_mode: host
    env_file:
      - path: .env
        required: false
    environment:
      - TZ=Europe/Warsaw
      - DOCKER_HOST=unix:///var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-k", "-sf", "https://localhost:8080"]
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 6
    entrypoint: ["/bin/bash", "/var/apps/coder/init.sh"]
    volumes:
      # 1. Workspace Access
      - /var/apps:/var/apps

      # 2. Docker Socket (Control host docker)
      - /var/run/docker.sock:/var/run/docker.sock

      # 4. Persistence (Config & Auth)
      - ./data/vscode:/home/coder/.local/share/code-server
      - ./data/continue:/home/coder/.continue
      - ./data/gcloud:/home/coder/.config/gcloud
      - ./data/ssh:/home/coder/.ssh
